# Generated by Django 4.2.2 on 2024-04-11 14:33

import Planet_Discoverers.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tagged_planets',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='planet_images/', validators=[Planet_Discoverers.photos.validators.validate_file_size]),
        ),
    ]
