# Generated by Django 4.2.2 on 2024-04-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photo_tagged_planets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tagged_planets',
        ),
    ]
