# Generated by Django 4.2.2 on 2024-04-12 12:20

import Planet_Discoverers.photos.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0007_remove_planet_photos'),
        ('photos', '0006_photo_planet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='planet_images/', validators=[Planet_Discoverers.photos.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planet_photos', to='planets.planet'),
        ),
    ]
