# Generated by Django 4.2.2 on 2024-04-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0009_alter_planet_photo'),
        ('photos', '0010_alter_photo_planet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='planet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planet_photos', to='planets.planet'),
        ),
    ]
