# Generated by Django 4.2.2 on 2024-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_alter_photo_planet'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_upload',
            field=models.ImageField(default='', upload_to='planet_images'),
        ),
    ]
