# Generated by Django 4.2.2 on 2024-04-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='size',
        ),
        migrations.AddField(
            model_name='planet',
            name='mass',
            field=models.PositiveIntegerField(default=1, help_text='Mass of the planet compared to planet Earth (how many Earths is it?)'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='description',
            field=models.TextField(help_text="Planet's characteristics, such as temperature, diameter, age, revolution, rotation, interesting facts, etc"),
        ),
    ]
