# Generated by Django 4.2.2 on 2024-04-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0003_planet_in_habitable_zone_planet_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='mass',
            field=models.FloatField(default=1, help_text='Mass of the planet compared to planet Earth (how many Earths is it?)'),
        ),
    ]
