# Generated by Django 4.2.2 on 2024-04-30 12:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('type', models.CharField(choices=[('Gas Giant', 'Gas Giant'), ('Super-Earth', 'Super-Earth'), ('Neptune-like', 'Neptune-like'), ('Terrestrial', 'Terrestrial')], default='')),
                ('in_habitable_zone', models.BooleanField(default=False)),
                ('mass', models.FloatField(default=1, help_text='(Mass of the planet compared to planet Earth (how many Earths is it?))')),
                ('description', models.TextField(help_text="(Planet's characteristics, such as temperature, diameter, age, revolution, rotation, interesting facts, etc)")),
                ('finding_method', models.CharField(choices=[('Transit Method', 'Transit Method'), ('Radial Velocity Method', 'Radial Velocity Method (Doppler Method)'), ('Direct Imaging', 'Direct Imaging'), ('Microlensing', 'Microlensing'), ('Astrometry', 'Astrometry'), ('Pulsar Timing', 'Pulsar Timing')], max_length=100)),
                ('primary_photo', models.ImageField(blank=True, null=True, upload_to='planet_images')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('discoverer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_upload', models.ImageField(default='', upload_to='planet_images')),
                ('description', models.TextField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('location', models.CharField(blank=True, help_text='Observatory location, only if finding method is Direct Imaging', max_length=30, null=True)),
                ('date_of_publication', models.DateField(auto_now=True)),
                ('planet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='planets.planet')),
            ],
        ),
    ]
