# Generated by Django 4.2.2 on 2024-04-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_remove_photo_tagged_planets_alter_photo_photo'),
        ('planets', '0004_alter_planet_mass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='planet_picture',
        ),
        migrations.AddField(
            model_name='planet',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='planets', to='photos.photo'),
        ),
    ]
