# Generated by Django 4.2.2 on 2024-04-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_remove_photo_tagged_planets'),
        ('planets', '0005_remove_planet_planet_picture_planet_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='photos',
        ),
        migrations.AddField(
            model_name='planet',
            name='photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.photo'),
        ),
    ]
