# Generated by Django 4.2.2 on 2024-04-12 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_alter_photo_photo_alter_photo_planet'),
        ('planets', '0007_remove_planet_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planet_photos', to='photos.photo'),
        ),
    ]
