# Generated by Django 4.2.2 on 2024-04-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0008_planet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
