# Generated by Django 4.2.2 on 2024-04-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0009_alter_planet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='description',
            field=models.TextField(help_text="(Planet's characteristics, such as temperature, diameter, age, revolution, rotation, interesting facts, etc)"),
        ),
        migrations.AlterField(
            model_name='planet',
            name='mass',
            field=models.FloatField(default=1, help_text='(Mass of the planet compared to planet Earth (how many Earths is it?))'),
        ),
    ]
